### ISSUE TITLE
 How to do do incremental build in LZMA (code example) ?

### ISSUE THREAD

**Issue by chfakht** [jljusten/LZMA-SDK#3]
Hi,

I'm working on LZMA decompressor , I want to know if i have a compressed file wich had been splitted to many files , How i could be able to decompress each file to reconstruct the original file ?
NB: i want to do this using LZMA SDK , I'm working in the code part of LzmaUtil.c not in 7-zip
Any help will be very appreciated , thanks

**Comment by jljusten** [comment]
@chfakht: This is just a mirror of the LZMA SDK source code.

The LZMA SDK site is at: http://www.7-zip.org/sdk.html
