### ISSUE TITLE
Using LZMA Compressor/decompressor to speed up the flashing board process

### ISSUE THREAD

**Issue by chfakht** [jljusten/LZMA-SDK#4]
Hi, Mr @jljusten
I'm using the LZMA SDK for file compression/decompression under Windows 7 (64 bits).
To compress the file i can use the following command.
./LzmaUtil.exe e input.elf output.elf
However , i want to split the resulted file into N separated files before , it could be even better if i could specify the max size of the splited files.
And on the other hand to be able to decompress all the separated files into a simple one file.
The command for splitting/re-assembling the files must be integrated into the source code.
The main purpose for this procedure is to reduce to time required for flashing the software into a micro-controller, the bootloader have to re-assemble and decopress all the files before flashing the outputed file (.elf/.bin) to memory. The flash is executed using a CAN BUS. The CAN BUS is able to send data by 8 bytes each frame . The data sent will be compressed using LZMA .I want to know if it's possible when receiving the data to decompress the 8 bytes or maybe i need to reassemble all the data before decompressing it.
What do you suggest Mr PAVLOV and can this be possible using LZMA , thanks
Any suggestions on how to do that. Thanks

**Comment by jljusten** [comment]
@chfakht: This is just a mirror of the LZMA SDK source code.

The LZMA SDK site is at: http://www.7-zip.org/sdk.html
