### ISSUE TITLE
This repository is not up to date with latest releases of lzma

### ISSUE THREAD

**Issue by Coeur** [jljusten/LZMA-SDK#6]
@jljusten, I'm aware of https://github.com/jljusten/lzma-sdk-to-git, but it would be nice to include the past 2-3 years releases of https://www.7-zip.org/sdk.html in the present github repository.

Their original repo is at https://sourceforge.net/projects/sevenzip/files/LZMA%20SDK/

**Comment by jljusten** [comment]
@Coeur: Hi. I added versions up through 18.05. Thanks!
